"""Python bridge for RootBuddy RL training."""

from .engine_client import (
    ConfigResponse,
    EngineClient,
    EngineClientError,
    EnvBatch,
    EnvDecision,
    Faction,
    ProtocolError,
    VecEnvConfig,
)
from .evaluate import (
    EvaluationConfig,
    EvaluationMetrics,
    GreedyVPAgent,
    ModelAgent,
    RandomAgent,
    evaluate_agents,
    load_model_from_checkpoint,
)
from .league import (
    FrozenModelAgent,
    LeaguePool,
    LeagueSnapshot,
    discover_snapshots,
    load_frozen_agent,
    parse_checkpoint_update,
)
from .model import (
    ActionEvaluation,
    ActionSelection,
    CandidatePolicyValueNet,
    ModelOutput,
    mask_logits,
    masked_categorical,
    tensors_from_batch,
)
from .ppo import (
    PPOBatch,
    PPOConfig,
    PPOLoss,
    PPOUpdateStats,
    compute_gae,
    iter_minibatches,
    normalize_advantages,
    ppo_loss,
    ppo_update,
)
from .rollout import (
    RolloutConfig,
    RolloutResult,
    RolloutStats,
    bootstrap_values,
    collect_rollout,
)
from .train import TrainConfig, TrainMetrics, TrainResult, build_model_from_batch, train
from .vec_env import RootBuddyVecEnv, VecEnvArrays, batch_to_arrays, sample_random_actions

__all__ = [
    "ActionEvaluation",
    "ActionSelection",
    "CandidatePolicyValueNet",
    "ConfigResponse",
    "EngineClient",
    "EngineClientError",
    "EnvBatch",
    "EnvDecision",
    "EvaluationConfig",
    "EvaluationMetrics",
    "Faction",
    "FrozenModelAgent",
    "GreedyVPAgent",
    "LeaguePool",
    "LeagueSnapshot",
    "ModelAgent",
    "ModelOutput",
    "PPOBatch",
    "PPOConfig",
    "PPOLoss",
    "PPOUpdateStats",
    "ProtocolError",
    "RandomAgent",
    "RolloutConfig",
    "RolloutResult",
    "RolloutStats",
    "RootBuddyVecEnv",
    "TrainConfig",
    "TrainMetrics",
    "TrainResult",
    "VecEnvConfig",
    "VecEnvArrays",
    "batch_to_arrays",
    "bootstrap_values",
    "build_model_from_batch",
    "collect_rollout",
    "compute_gae",
    "discover_snapshots",
    "evaluate_agents",
    "iter_minibatches",
    "load_model_from_checkpoint",
    "load_frozen_agent",
    "mask_logits",
    "masked_categorical",
    "normalize_advantages",
    "parse_checkpoint_update",
    "ppo_loss",
    "ppo_update",
    "sample_random_actions",
    "tensors_from_batch",
    "train",
]
