package server

import "net/http"

func NewServer() http.Handler {
	mux := http.NewServeMux()
	mux.HandleFunc("GET /health", HandleHealthCheck)
	mux.HandleFunc("GET /api/health", HandleHealthCheck)
	mux.HandleFunc("POST /actions/valid", HandleValidActions)
	mux.HandleFunc("POST /api/actions/valid", HandleValidActions)
	mux.HandleFunc("POST /actions/apply", HandleApplyAction)
	mux.HandleFunc("POST /api/actions/apply", HandleApplyAction)
	mux.HandleFunc("POST /battles/resolve", HandleResolveBattle)
	mux.HandleFunc("POST /api/battles/resolve", HandleResolveBattle)
	mux.HandleFunc("POST /battles/context", HandleBattleContext)
	mux.HandleFunc("POST /api/battles/context", HandleBattleContext)
	mux.HandleFunc("POST /game/setup", HandleSetup)
	mux.HandleFunc("POST /api/game/setup", HandleSetup)
	mux.HandleFunc("POST /game/load", HandleLoadGame)
	mux.HandleFunc("POST /api/game/load", HandleLoadGame)
	mux.HandleFunc("POST /lobby/create", HandleCreateLobby)
	mux.HandleFunc("POST /api/lobby/create", HandleCreateLobby)
	mux.HandleFunc("POST /lobby/join", HandleJoinLobby)
	mux.HandleFunc("POST /api/lobby/join", HandleJoinLobby)
	mux.HandleFunc("GET /lobby/state", HandleLobbyState)
	mux.HandleFunc("GET /api/lobby/state", HandleLobbyState)
	mux.HandleFunc("POST /lobby/claim-faction", HandleClaimFaction)
	mux.HandleFunc("POST /api/lobby/claim-faction", HandleClaimFaction)
	mux.HandleFunc("POST /lobby/ready", HandleLobbyReady)
	mux.HandleFunc("POST /api/lobby/ready", HandleLobbyReady)
	mux.HandleFunc("POST /lobby/start", HandleStartLobby)
	mux.HandleFunc("POST /api/lobby/start", HandleStartLobby)
	mux.HandleFunc("POST /lobby/leave", HandleLeaveLobby)
	mux.HandleFunc("POST /api/lobby/leave", HandleLeaveLobby)
	return withCORS(mux)
}
