const cardLabels: Record<number, string> = {
  [-2]: "Loyal Vizier",
  [-1]: "Loyal Vizier",
  1: "Armorers (Bird)",
  2: "Armorers (Bird)",
  3: "Sappers (Bird)",
  4: "Sappers (Bird)",
  5: "Brutal Tactics (Bird)",
  6: "Brutal Tactics (Bird)",
  7: "Royal Claim (Bird)",
  8: "Birdy Bindle (Bird)",
  9: "Woodland Runners (Bird)",
  10: "Arms Trader (Bird)",
  11: "Crossbow (Bird)",
  12: "Ambush (Bird)",
  13: "Ambush (Bird)",
  14: "Dominance (Bird)",
  15: "Better Burrow Bank (Rabbit)",
  16: "Better Burrow Bank (Rabbit)",
  17: "Cobbler (Rabbit)",
  18: "Cobbler (Rabbit)",
  19: "Command Warren (Rabbit)",
  20: "Command Warren (Rabbit)",
  21: "Bake Sale (Rabbit)",
  22: "Smuggler's Trail (Rabbit)",
  23: "Root Tea (Rabbit)",
  24: "A Visit to Friends (Rabbit)",
  25: "Favor of the Rabbits (Rabbit)",
  26: "Ambush (Rabbit)",
  27: "Dominance (Rabbit)",
  28: "Codebreakers (Mouse)",
  29: "Codebreakers (Mouse)",
  30: "Scouting Party (Mouse)",
  31: "Scouting Party (Mouse)",
  32: "Crossbow (Mouse)",
  33: "Sword (Mouse)",
  34: "Travel Gear (Mouse)",
  35: "Investments (Mouse)",
  36: "Favor of the Mice (Mouse)",
  37: "Root Tea (Mouse)",
  38: "Mouse-in-a-Sack (Mouse)",
  39: "Ambush (Mouse)",
  40: "Dominance (Mouse)",
  41: "Stand and Deliver! (Fox)",
  42: "Stand and Deliver! (Fox)",
  43: "Tax Collector (Fox)",
  44: "Tax Collector (Fox)",
  45: "Tax Collector (Fox)",
  46: "Root Tea (Fox)",
  47: "Protection Racket (Fox)",
  48: "Travel Gear (Fox)",
  49: "Gently Used Knapsack (Fox)",
  50: "Favor of the Foxes (Fox)",
  51: "Foxfolk Steel (Fox)",
  52: "Anvil (Fox)",
  53: "Ambush (Fox)",
  54: "Dominance (Fox)"
};

export function describeKnownCardID(cardID: number): string {
  return cardLabels[cardID] ?? `Card ${cardID}`;
}

export function describeKnownCardIDs(cardIDs: number[]): string {
  return cardIDs.map(describeKnownCardID).join(", ");
}
